### ISSUE TITLE
hi bro, wheather this lib support muti-track or not？

### ISSUE THREAD

**Issue by slgluo** [BouKiCHi/mmlc_py#1]
like this :
v72t120a8c8e8;
v68t120c8e8g8

they are split by a semicolon（；）

**Comment by slgluo** [comment]
Could you add some examples?

**Comment by BouKiCHi** [comment]
I didn't explain it well enough.

This is a compiler for MML, available at the following URL
https://m2stg.com/senxin-aleste/mml.php

**Comment by slgluo** [comment]
> I didn't explain it well enough.
> 
> This is a compiler for MML, available at the following URL
> https://m2stg.com/senxin-aleste/mml.php

This syntax is much more complicated than which I use. Although it didn't solve my problem, thanks bro !
